language: rust
rust:
  - nightly
matrix:
  fast_finish: true
cache: cargo

sudo: required
services:
  - docker

script:
  - cargo test --verbose --all

deploy:
  - provider: script
    on:
      tags: true
    script: ./deploy.sh
    skip_cleanup: true
