language: rust
rust:
  - nightly
matrix:
  fast_finish: true
cache: cargo

sudo: required
services:
  - docker

if: tag IS present OR type = pull_request

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script:
  - cargo test --verbose --all

deploy:
  - provider: script
    on:
      tags: true
    script: ./deploy.sh
    skip_cleanup: true
