[package]
name = "signed-urls"
version = "0.1.0"
authors = ["Robert den Harink <robert@robhar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.5"
hmac = "0.7.1"
sha2 = "0.8.0"
chrono = "0.4.9"